### ISSUE TITLE
Errors trying to run react-components

### ISSUE THREAD

**Issue by djtfmartin** [gbif/gbif-web#134]
I get this error when trying to run the react-components module following the instructions in the README.

```
(node:95302) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 1/1 modules 0 active/Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13
    mainCompilation.fileSystemInfo.createSnapshot(
                                   ^

TypeError: Cannot read properties of undefined (reading 'createSnapshot')
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
```

I get this error with node version 17.4.0, 16.14.2 and 13.7.0 (which is the version specified in .nvmrc)

**Comment by timrobertson100** [comment]
What happens if you delete `package-lock.json`, the `node_modules` folder, and then run `npm install --legacy-peer-deps` please?

**Comment by djtfmartin** [comment]
same error - ive tried this

**Comment by djtfmartin** [comment]
```
npm install --reg https://repository.gbif.org/content/repositories/npmjs/
```

times out i'm afraid:

```
 npm install --reg https://repository.gbif.org/content/repositories/npmjs/
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mar759/.npm/_logs/2022-04-12T10_57_42_509Z-debug-0.log
```

**Comment by djtfmartin** [comment]
Same error after running 

```
npm install --reg https://repository.gbif.org/content/repositories/npmjs/
npm run --reg https://repository.gbif.org/content/repositories/npmjs/ build-client
```

and then 

```
npm run start
```

**Comment by timrobertson100** [comment]
I just set up a mac with the following and can confirm it does work. Let's try and see how your environment and the ones we use here differ. Here is what I did.

- `nvm` (using brew)
- `node` using `nvm use 3.17.0`
- a new `xcode` install as I had updated OSX
- a fresh checkout of this repository 
- the .env.json as below

Within the `packages/react-components`, running `npm install && npm run start` seemed to all work OK, resulting in the browser showing the same as https://react-components.gbif.org/

```
{
  "API_V1": "https://api.gbif.org/v1",
  "API_V2": "https://api.gbif.org/v2",
  "GRAPH_API": "https://graphql.gbif-staging.org/graphql",
  "TILE_API": "https://hp-maps.gbif-staging.org",
  "MAPBOX_KEY": "noneYaBusiness",
  "DOMAIN": "react-components.gbif-staging.org",
  "GBIF_ORG": "https://www.gbif.org",
  "TRANSLATIONS": "https://react-components.gbif-staging.org/lib/translations",
  "LOCALES": ["en-developer", "en-pseudo", "en", "da", "ar", "da", "de", "es", "fa", "fj", "fr", "ja", "la", "niu", "nl", "pis", "pt", "ru", "sm", "sw", "tkl", "to", "tvl", "uk", "zh", "zh-tw"]
}
```

**Comment by djtfmartin** [comment]
I've done the following

* Updated Xcode
* Ran `npm cache clean --force`
* Deleted `node_modules` and `package-locked.json`
* Verified node version to be 13.7.0
* Included the JSON in `.env.json` (need to add to README)

Slightly different error than before, but still not running for me:

```
(node:26103) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
info => Loading presets
info => Using implicit CSS loaders
info => Using default Webpack4 setup
(node:26103) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
10% building 1/1 modules 0 active(node:26103) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
(node:26103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:26103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10% building 2/6 modules 4 active /Users/mar759/dev/gbif-web/packages/react-components/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
info => Ignoring cached manager due to change in manager config
10% building 5/9 modules 4 active /Users/mar759/dev/gbif-web/packages/react-components/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefinedℹ ｢wdm｣: wait until bundle finished: 
(node:26103) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/mar759/dev/gbif-web/packages/react-components/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
```

**Comment by MattBlissett** [comment]
Using Docker, which you can hopefully reproduce reliable. Note it's Node 16:

```shell
> pwd
.../gbif-web
> ls -l packages/react-components/.env.json
-rw-r--r-- 1 matt blissett 515 2022-04-12 21:11 packages/react-components/.env.json
> docker run --rm -i -t -v $PWD:/home/node/app node:16 /bin/bash
root@0898fce58948:/# node --version
v16.13.1
root@0898fce58948:/# npm --version
8.1.2
root@0898fce58948:/# cd /home/node/app/packages/react-components/
root@0898fce58948:/home/node/app/packages/react-components# npm install --reg https://repository.gbif.org/content/repositories/npmjs/
...
root@0898fce58948:/home/node/app/packages/react-components# npm run --reg https://repository.gbif.org/content/repositories/npmjs/ build-client
...
root@0898fce58948:/home/node/app/packages/react-components# ls -l dist
total 7176
-rw-r--r-- 1 1001 node    4456 Apr 12 19:17 0.196fda15.iframe.bundle.js
-rw-r--r-- 1 1001 node   96701 Apr 12 19:17 0.19a049bc89adbaabdaf2.manager.bundle.js
-rw-r--r-- 1 1001 node     193 Apr 12 19:17 0.19a049bc89adbaabdaf2.manager.bundle.js.LICENSE.txt
-rw-r--r-- 1 1001 node   66589 Apr 12 19:17 1.a31188b59a71cb147631.manager.bundle.js
-rw-r--r-- 1 1001 node   35780 Apr 12 19:17 5.f2159bc0766fe0e29ed1.manager.bundle.js
-rw-r--r-- 1 1001 node  149091 Apr 12 19:17 6.a0a258e0a8200c11ccc8.manager.bundle.js
-rw-r--r-- 1 1001 node     227 Apr 12 19:17 6.a0a258e0a8200c11ccc8.manager.bundle.js.LICENSE.txt
-rw-r--r-- 1 1001 node   11226 Apr 12 19:17 7.bfc1c1c32a001c7248cb.manager.bundle.js
-rw-r--r-- 1 1001 node    1001 Apr 12 19:17 8.7ba387238d897fcd7ac6.manager.bundle.js
-rw-r--r-- 1 1001 node   32988 Apr 12 19:08 favicon.ico
-rw-r--r-- 1 1001 node   11803 Apr 12 19:17 iframe.html
-rw-r--r-- 1 1001 node    2118 Apr 12 19:17 index.html
drwxr-xr-x 2 1001 node    4096 Apr 12 19:17 lib
-rw-r--r-- 1 1001 node 1485026 Apr 12 19:17 main.d8670ecd.iframe.bundle.js
-rw-r--r-- 1 1001 node     343 Apr 12 19:17 main.e1b64a4dcabd4ddd8f67.manager.bundle.js
-rw-r--r-- 1 1001 node    4384 Apr 12 19:17 runtime~main.a61c8006.iframe.bundle.js
-rw-r--r-- 1 1001 node    4522 Apr 12 19:17 runtime~main.c4f73a46432089b26dab.manager.bundle.js
-rw-r--r-- 1 1001 node 2272480 Apr 12 19:17 vendors~main.8a7e074859c727569ee8.manager.bundle.js
-rw-r--r-- 1 1001 node    2621 Apr 12 19:17 vendors~main.8a7e074859c727569ee8.manager.bundle.js.LICENSE.txt
-rw-r--r-- 1 1001 node 3105432 Apr 12 19:17 vendors~main.d76463f7.iframe.bundle.js
-rw-r--r-- 1 1001 node    3666 Apr 12 19:17 vendors~main.d76463f7.iframe.bundle.js.LICENSE.txt
-rw-r--r-- 1 1001 node     106 Apr 12 19:17 vendors~main.d76463f7.iframe.bundle.js.map
```

There are some warnings, but it seems to have built.

**Comment by MattBlissett** [comment]
I see `.nvmrc` says version 13.7.0, but the build server is using Node 16.

**Comment by djtfmartin** [comment]
Just to update - this is still an issue for me

I haven't tried Matt's suggestion, but I will when I put more time to this.

**Comment by djtfmartin** [comment]
Fixed by running `npm audit fix` and `npm i --save-dev html-webpack-plugin`
