### ISSUE TITLE
Error in database of colecction MOBO

### ISSUE THREAD

**Issue by Ana-Ruiz** [gbif/gbif-web#379]
Thank you for reporting this issue. Please describe what happened.

**Error message for diagnostics**
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Dh (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:133:303)
    at Aj (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:158:298)
    at unstable_runWithPriority (https://unpkg.com/react@16/umd/react.production.min.js:25:260)
    at Da (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:60:280)
    at ab (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:154:190)
    at Te (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:146:355)
    at https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:61:68
    at unstable_runWithPriority (https://unpkg.com/react@16/umd/react.production.min.js:25:260)
    at Da (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:60:280)
    at Pg (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:61:14)
```
Location: https://scientific-collections.gbif.org/institution/1be3aa67-8f90-4309-92f4-bd55426a8c09/specimens?taxonKey=2877951

**Comment by MortenHofft** [comment]
Thanks for reporting that @Ana-Ruiz 
The page itself seem to work when i click around. Do you remember what you did that triggered this error?
