### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#428]
The gbif-web project doesn't build.

```
"loader" is not exported by "src/routes/occurrence/search/OccurrenceSearchPage.tsx", imported by "src/hp/routes.tsx".
file: /usr/src/app/src/hp/routes.tsx:12:2
10: import {
11:   OccurrenceSearchPage,
12:   loader as occurrenceSearchLoader,
      ^
13: } from '@/routes/occurrence/search/OccurrenceSearchPage';
14: import { Config } from '@/contexts/config';
error during build:
RollupError: "loader" is not exported by "src/routes/occurrence/search/OccurrenceSearchPage.tsx", imported by "src/hp/routes.tsx".
    at error (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at Identifier.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at Property.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at ObjectExpression.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at ArrayExpression.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Property.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at ObjectExpression.bind (file:///usr/src/app/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
Build step 'Execute shell' marked build as failure
New run name is '#950 staging - master'
```

@danielvdm2000 could you please prioritize getting this fixed.

**Comment by danielvdm2000** [comment]
The invalid import has been removed
