### ISSUE TITLE
had administrative filter "roskilde" applied, clicked "Galleri"

### ISSUE THREAD

**Issue by DanBIF** [gbif/gbif-web#460]
Thank you for reporting this issue. Please describe what happened.

**Error message for diagnostics**
```
TypeError: Cannot read properties of null (reading 'formattedName')
    at https://react-components.gbif-staging.org/lib/gbif-react-components.js?v=031fb426a979e00c8f75921e8e42d8c5:68:275312
    at Array.map (<anonymous>)
    at Ac (https://react-components.gbif-staging.org/lib/gbif-react-components.js?v=031fb426a979e00c8f75921e8e42d8c5:68:274745)
    at we (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:84:293)
    at He (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:97:464)
    at zj (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:228:406)
    at Th (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:152:223)
    at tj (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:152:152)
    at Te (https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:146:151)
    at https://unpkg.com/react-dom@16/umd/react-dom.production.min.js:61:68
```
Location: https://danbif.hp.gbif-staging.org/occurrence/search?gadmGid=DNK.4.12_1&view=GALLERY

**Comment by MortenHofft** [comment]
That is annoying, but I cannot reproduce it. Can you?

My best guess at this point is an API glitch that might be handled better (with a retry probably)

**Comment by DanBIF** [comment]
can't reproduce, tried with another area also (Høje Taastrup). You cal close issue if you want
