### ISSUE TITLE
Error Message When You Click A Collection

### ISSUE THREAD

**Issue by zeenbean01** [gbif/gbif-web#597]
Thank you for reporting this issue. Please describe what happened.

When I click on a specific collection, an error message pops up. For example, when I click Fish Collection, there is an error that says something went wrong. 

**Error message for diagnostics**
```
Error: Error: GraphQL error: 503: Backend fetch failed
    at LO (https://react-components.gbif.org/lib/gbif-react-components.js?v=c486aa8cdc3578b030b7a9d57318120d:68:504343)
    at Le (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:100:3)
    at Re (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:113:271)
    at Pj (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:233:55)
    at di (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:305)
    at Nj (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:236)
    at sc (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:96)
    at gf (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:162:109)
    at https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:73:230
    at unstable_runWithPriority (https://unpkg.com/react@17.0.1/umd/react.production.min.js:24:26)
```
Location: https://collections.beatymuseum.ubc.ca/collection/5aee131f-91dd-4b78-bfee-296f86801b7f

**Comment by MortenHofft** [comment]
Thank you for reporting this. We had an outage for several hours that day as we were being hammered with requests. I'm not sure about the details of why it happened (if it was a deliberate attack or just lack of knowledge). It is one of the dangers of providing a completely open and free service I'm afraid.

I think the best we can do in the interface in these cases, is to provide a clearer message that our services are temporarily out of error. And ideally state the reason and duration if we know it.

We do that on [gbif.org](https://www.gbif.org/system-health) but there isn't something similar on these hosted portals (like Grscicoll). We should add that.

**Comment by MortenHofft** [comment]
I've created an issue for adding status pages to hosted portals here https://github.com/gbif/gbif-web/issues/599
