### ISSUE TITLE
bug: rendering fewer hooks than expected

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#629]
`/ipt` returned an error about rendering fewer hooks than expected. No other information. Running locally.

**Comment by MortenHofft** [comment]
happened again. here is the log statement
```
console.js:288 React Router caught the following error during render 
Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (chunk-PIFOP4FQ.js?v=64ab41f5:21244:21)
    at updateReducer (chunk-PIFOP4FQ.js?v=64ab41f5:21293:22)
    at updateState (chunk-PIFOP4FQ.js?v=64ab41f5:21587:18)
    at Object.useState (chunk-PIFOP4FQ.js?v=64ab41f5:22319:24)
    at useState (chunk-67CBG26T.js?v=64ab41f5:3438:29)
    at Object.RenderIfChildren [as type] (renderIfChildren.tsx:16:33)
    at willRenderToNull (renderIfChildren.tsx:47:38)
    at willRenderToNull (renderIfChildren.tsx:47:12)
    at Array.every (<anonymous>)
    at willRenderToNull (renderIfChildren.tsx:37:21)
 
{componentStack: '\n    at RenderIfChildren (http://localhost:3000/sr…//localhost:3000/src/components/root.tsx:2137:24)'}
 
    at RenderErrorBoundary (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5510:5)
    at Outlet (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5872:26)
    at main
    at GbifRootLayout (http://localhost:3000/src/gbif/gbifRootLayout.tsx:2168:34)
    at LoadingElementWrapper (http://localhost:3000/src/components/loadingElementWrapper.tsx:2133:41)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5550:5)
    at Outlet (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5872:26)
    at IntlProvider3 (http://localhost:3000/node_modules/.vite/deps/react-intl.js?v=64ab41f5:6458:45)
    at I18nProvider (http://localhost:3000/src/contexts/i18n.tsx:2137:32)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5550:5)
    at RenderErrorBoundary (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5510:5)
    at DataRoutes (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:6529:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:5879:15)
    at RouterProvider (http://localhost:3000/node_modules/.vite/deps/chunk-VR3NC37L.js?v=64ab41f5:6392:5)
    at Provider (http://localhost:3000/node_modules/.vite/deps/chunk-ZHNKJH77.js?v=64ab41f5:2160:15)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (http://localhost:3000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=64ab41f5:2199:11)
    at r2 (http://localhost:3000/node_modules/.vite/deps/react-helmet-async.js?v=64ab41f5:2413:21)
    at LoadingElementProvider (http://localhost:3000/src/contexts/loadingElement.tsx:2136:42)
    at MetadataRoutesProvider (http://localhost:3000/src/contexts/metadataRoutes.tsx:2134:42)
    at ConfigProvider (http://localhost:3000/src/contexts/config/config.tsx:2135:34)
    at Root (http://localhost:3000/src/components/root.tsx:2137:24)

```

**Comment by MortenHofft** [comment]
@danielvdm2000 It looks like it is the `RenderIfChildren` component

**Comment by MortenHofft** [comment]
Okay that error happens all the time. in prod build as well
https://react.dev/errors/300?invariant=300
