### ISSUE TITLE
Details drawer

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#762]
* [x] #828
* [x] The data header should not be displayed in the drawers (there is a config option to remove the selector, but the drawer do not set it)

**Comment by MortenHofft** [comment]
aria issues. You can probably fix this easily @danielvdm2000 
```
Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}. Error Component Stack
    at DescriptionWarning (@radix-ui_react-dialog.js?v=f8679f9c:3679:29)
    at @radix-ui_react-dialog.js?v=f8679f9c:3583:13
    at @radix-ui_react-dialog.js?v=f8679f9c:3506:58
    at Presence (@radix-ui_react-dialog.js?v=f8679f9c:2916:11)
    at @radix-ui_react-dialog.js?v=f8679f9c:3497:64
    at div (<anonymous>)
    at @radix-ui_react-dialog.js?v=f8679f9c:2447:13
    at @radix-ui_react-dialog.js?v=f8679f9c:2369:11
    at @radix-ui_react-dialog.js?v=f8679f9c:2350:11
    at @radix-ui_react-dialog.js?v=f8679f9c:3067:21
    at @radix-ui_react-dialog.js?v=f8679f9c:3477:13
    at Presence (@radix-ui_react-dialog.js?v=f8679f9c:2916:11)
    at @radix-ui_react-dialog.js?v=f8679f9c:3468:64
    at @radix-ui_react-dialog.js?v=f8679f9c:2369:11
    at @radix-ui_react-dialog.js?v=f8679f9c:2350:11
    at @radix-ui_react-dialog.js?v=f8679f9c:2447:13
    at @radix-ui_react-dialog.js?v=f8679f9c:2896:22
    at Presence (@radix-ui_react-dialog.js?v=f8679f9c:2916:11)
    at Provider (@radix-ui_react-dialog.js?v=f8679f9c:2204:15)
    at DialogPortal (@radix-ui_react-dialog.js?v=f8679f9c:3460:11)
    at Provider (@radix-ui_react-dialog.js?v=f8679f9c:2204:15)
    at Dialog (@radix-ui_react-dialog.js?v=f8679f9c:3401:5)
    at Drawer (drawer.tsx:23:3)
    at EntityDrawer (ListBrowser.tsx:21:27)
```

**Comment by MortenHofft** [comment]
@danielvdm2000 When on gallery view the body scrolls to top when opening the occurrence sidebar. This is disturbing the flow of exploration and differs from current behaviour on production site
