### ISSUE TITLE
Error message when trying to open resource

### ISSUE THREAD

**Issue by ElianaWalker** [gbif/gbif-web#763]
Thank you for reporting this issue. Please describe what happened.
![Image](https://github.com/user-attachments/assets/9896cb7e-57d9-40c8-b097-c4d224df6e3a)

I get this message when I try to open the dataset. 

thank you

**Error message for diagnostics**
```
Error: Error: GraphQL error: 401: Unauthorized
    at Ve (https://react-components.gbif.org/lib/gbif-react-components.js?v=1659e557b2996606a171337381228729:18:1860553)
    at Le (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:100:3)
    at Re (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:113:271)
    at Pj (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:233:55)
    at di (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:305)
    at Nj (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:236)
    at sc (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:168:96)
    at gf (https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:162:109)
    at https://unpkg.com/react-dom@17.0.1/umd/react-dom.production.min.js:73:230
    at unstable_runWithPriority (https://unpkg.com/react@17.0.1/umd/react.production.min.js:24:26)
```
Location: https://sibuy.ambiente.gub.uy/dataset/1d68f3a2-6b42-437d-a0f7-e850d74e0e9f

**Comment by MortenHofft** [comment]
Thanks for reporting this.
This dataset have a reference to Catalogue of Life. But their API says we are not allowed to show it and so the page fails. 
https://api.checklistbank.org/dataset/gbif-1d68f3a2-6b42-437d-a0f7-e850d74e0e9f.json

We should look at failing more gracefully in this case. But the crux of the issue is that we either rely in CoL in  a way we cannot or alternatively that CoL have a bug? I'm not sure which is the case.

@mdoering can you help me here please?

**Comment by mdoering** [comment]
Hi. The dataset is indeed private on checklistbank, so it needs authorisation to view it.
It is not related to COL though, just a GBIF dataset which probably should be public:
https://www.gbif.org/dataset/1d68f3a2-6b42-437d-a0f7-e850d74e0e9f

I'll try to figure out why it is private

**Comment by mdoering** [comment]
I've found it. We switched to private default datasets a few weeks ago and the gbif sync job wasn't adapted to that and made all new gbif datasets private since. I am changing their state manually in the db now.

**Comment by ElianaWalker** [comment]
Now it works perfectly. 

Thank you Morten and Markus.
